# Generated by Django 4.1.4 on 2023-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=200)),
                ('rate', models.FloatField()),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
