# Generated by Django 4.1.4 on 2023-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerestaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='timeStamp',
            field=models.DateField(blank=True),
        ),
    ]
