# Generated by Django 4.1.4 on 2023-01-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerestaurants', '0002_alter_restaurants_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='rimg',
            field=models.ImageField(default='', max_length=250, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
