# Generated by Django 4.1.4 on 2023-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerestaurants', '0004_restaurants_openclose_restaurants_restauranttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
